### ISSUE TITLE
rhel8stig_audit_complex not defined

### ISSUE THREAD

**Issue by sgomez86** [ansible-lockdown/RHEL8-CIS#1]
I was getting and ansible error when arriving to line 214 of section6 as rhel8stig_audit_complex is not defined anywhere on the role.

by removing 

```
changed_when:
            - rhel8stig_audit_complex
```
It works OK

**Comment by georgenalen** [comment]
Thanks for creating a ticket on this issue, we have updated the changes to the devel branch. It will be making it's way into Master soon


-George
