### ISSUE TITLE
2.2.2 | PATCH | Ensure X Window System is not installed | remove packages if found

### ISSUE THREAD

**Issue by RosarioVinoth** [ansible-lockdown/RHEL8-CIS#102]
Hi,

Quick and simple one, xorg_x11_installed.stdout below has to be as variable and stdout_lines may be used.

   - name: "SCORED | 2.2.2 | PATCH | Ensure X Window System is not installed | remove packages if found"
        shell: "dnf remove {{ item }}"
        with_items:
            **- xorg_x11_installed.stdout**
        when: xorg_x11_installed.stdout | length > 0

**Comment by uk-bolly** [comment]
@RosarioVinoth 

Thank you for taking the time to highlight this. 
I will be pushing a new branch up later today incorporating this issue.

uk-bolly

**Comment by uk-bolly** [comment]
@RosarioVinoth 

This has now been pushed into devel.
Thank you again for highlighting this improvement.

uk-bolly
