### ISSUE TITLE
SCORED | 5.4.1 | PATCH | Ensure password creation requirements are configured | Set pwquality config settings

### ISSUE THREAD

**Issue by RosarioVinoth** [ansible-lockdown/RHEL8-CIS#104]
Hi,

The regexp is looking for target config settings instead of just minlen/minclass with any value.

 - name: "SCORED | 5.4.1 | PATCH | Ensure password creation requirements are configured | Set pwquality config settings"
        lineinfile:
            state: present
            dest: /etc/security/pwquality.conf
            **regexp: '^{{ item }}'
            line: '{{ item }}'**
        with_items:
            **- "minlen = {{ rhel8cis_pam_password.minlen }}"
            - "minclass = {{ rhel8cis_pam_password.minclass }}"**
        when: rhel8cis_rule_5_4_1

Thanks.

**Comment by uk-bolly** [comment]
Hi @RosarioVinoth 

Thank you for raising the issue. If i understand your question? It is expected the regexp should be looking for any value in the minclass/minlength settings.
The actual step is settings the value to be that figure as specified.
These settings can be found in the default/main.yml file. This allows you to set the requirements that are needed on a per site settings. The defaults we have added are as per the suggested in CIS. Although you may require stronger or weaker setting dependent on your own requirements.
Please let us know if we may have misunderstood something.

Many thanks once again for taking the time.

uk-bolly

**Comment by RosarioVinoth** [comment]
@uk-bolly,

Thanks for your great work, i would try to do tiny part.

So the regexp is looking for target value as in 'minclass = 4' instead of like '^minclass = '.
This case, if the existing value is 'minclass = 3', it is not getting replaced by 'minclass =4' but new line is added.

So i get double entries.

#grep -v ^# /etc/security/pwquality.conf | grep min
minlen = 6
minclass = 3
minlen = 14
minclass = 4
#  
 
I did something like this to get through.

      - name: "SCORED | 5.4.1.a | PATCH | Ensure password creation requirements are configured | Set pwquality config settings"
        lineinfile:
            state: present
            dest: /etc/security/pwquality.conf
            regexp: '^minlen'
            line: 'minlen = {{ rhel8cis_pam_password.minlen }}'
        when: rhel8cis_rule_5_4_1
      - name: "SCORED | 5.4.1.b | PATCH | Ensure password creation requirements are configured | Set pwquality config settings"
        lineinfile:
            state: present
            dest: /etc/security/pwquality.conf
            regexp: '^minclass'
            line: 'minclass = {{ rhel8cis_pam_password.minclass }}'

Thanks.

**Comment by uk-bolly** [comment]
hi @RosarioVinoth 

I have now raised the fix for this issue. Thank you for explaining the issue and providing an example solution.
The PR is now raised and hopefully will be approved over the next week.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @RosarioVinoth 

The merge was commited a little while ago. Can you confirm that this has resolved the original issue for you?

Thanks once again

uk-bolly

**Comment by uk-bolly** [comment]
Closing Issue as in place for 1 month now.

Thanks

uk-bolly
