### ISSUE TITLE
item 6.2.7 failes with template error

### ISSUE THREAD

**Issue by erpadmin** [ansible-lockdown/RHEL8-CIS#111]
TASK [RHEL8-CIS : SCORED | 6.2.7| AUDIT | Ensure users' home directories permissions are 750 or more restrictive] ********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TemplateRuntimeError: no test named '>='
fatal: [ansibletest.localnet]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

I believe this is the trigger:
with_items: "{{ rhel8cis_passwd | selectattr('uid', '>=', rhel8cis_int_gid) | selectattr('uid', '!=', 65534) | map(attribute='dir' ) | list }}"

$ ansible --version
ansible 2.9.21
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

**Comment by erpadmin** [comment]
this was solved  with python3 env + ansible.   something along the lines of JInga2 templates being needed.

**Comment by uk-bolly** [comment]
hi @erpadmin 

If you believe that this issue is now resolved? Are you happy to close this?

Thanks

Uk-bolly

**Comment by uk-bolly** [comment]
closing as per previous comment
