### ISSUE TITLE
-list-tags does not produce expected output

### ISSUE THREAD

**Issue by adds68** [ansible-lockdown/RHEL8-CIS#145]
**Describe the Issue**
ansible-playbook site.yml –list-tags produces an error

**Expected Behavior**
According to the getting started page this should list all available tags

**Actual Behavior**
`➜  RHEL8-CIS git:(devel) ✗ ansible-playbook site.yml –list-tags
[DEPRECATION WARNING]: COMMAND_WARNINGS option, the command warnings feature is being removed. This feature will be removed from ansible-core in version 2.14. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ERROR! the playbook: –list-tags could not be found`

**Control(s) Affected**
What controls are being affected by the issue

**Environment (please complete the following information):**
 - Ansible Version: ansible [core 2.11.3] 
 - Host Python Version: Python 3.9.7

**Additional Notes**
Anything additional goes here

**Possible Solution**
Enter a suggested fix here

**Comment by uk-bolly** [comment]
Hi @adds68 

Thank you for taking the time to feedback on this repository. Apologies it has taken so longer to respond to your queries than normal.

- Looking at the issue with listing tags.

I can see in the command that you have run it is complaining about not finding a playbook called --list-tags. By moving around the order of list-tags and the site.yml this does produce output and I am able to see the following (below).

I am hoping that helps with your issue if not, could you provide more information on what is missing, I haven't gone through every tag but if there is something you expect please let us know so we can rectify any issue.



Best regards

uk-bolly



 ( I have left warning for clarity)
ansible-playbook --list-tags site.yml                                                                                       
[DEPRECATION WARNING]: COMMAND_WARNINGS option, the command warnings feature is being removed. This feature will be removed from ansible-core in version 2.14. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

playbook: site.yml

  play #1 (all): all    TAGS: []
      TASK TAGS: [aide, always, audit, auditd, authselect, automounting, avahi, banner, cramfs, cups, dhcp, file_integrity, goss_template, grub, ldap, level1, level1-server, level1-workstation, level2-server, level2-workstation, mounts, nfs, no system_is_ec2, not system_is_ec2, notscored, patch, permissons, perms, post_tasks, prelim_tasks, removable_storage, rhel8cis_section1, rpc, rsyslog, rule_1.1.1.1, rule_1.1.1.2, rule_1.1.1.3, rule_1.1.1.4, rule_1.1.11, rule_1.1.12, rule_1.1.13, rule_1.1.15, rule_1.1.16, rule_1.1.17, rule_1.1.18, rule_1.1.19, rule_1.1.20, rule_1.1.21, rule_1.1.22, rule_1.1.23, rule_1.1.3, rule_1.1.4, rule_1.1.5, rule_1.1.6, rule_1.1.7, rule_1.10, rule_1.11, rule_1.2.1, rule_1.2.2, rule_1.2.3, rule_1.2.4, rule_1.2.5, rule_1.3.1, rule_1.3.2, rule_1.3.3, rule_1.4.1, rule_1.4.2, rule_1.5.1, rule_1.5.2, rule_1.5.3, rule_1.6.1, rule_1.6.2, rule_1.7.1.1, rule_1.7.1.2, rule_1.7.1.3, rule_1.7.1.4, rule_1.7.1.5, rule_1.7.1.6, rule_1.7.1.7, rule_1.8.1.1, rule_1.8.1.2, rule_1.8.1.3, rule_1.8.1.4, rule_1.8.1.5, rule_1.8.1.6, rule_1.9, rule_2.1.1, rule_2.2.1, rule_2.2.1.1, rule_2.2.1.2, rule_2.2.10, rule_2.2.11, rule_2.2.12, rule_2.2.15, rule_2.2.16, rule_2.2.17, rule_2.2.2, rule_2.2.3, rule_2.2.4, rule_2.2.5, rule_2.2.6, rule_2.2.7, rule_2.2.8, rule_2.2.9, rule_2.3.1, rule_2.3.2, rule_2.3.3, rule_3.1.1, rule_3.1.2, rule_3.2.1, rule_3.2.2, rule_3.2.3, rule_3.2.4, rule_3.2.5, rule_3.2.6, rule_3.2.7, rule_3.2.8, rule_3.2.9, rule_3.3.1, rule_3.3.2, rule_3.3.3, rule_3.3.4, rule_3.4.1.1, rule_3.4.2.4, rule_3.4.2.5, rule_3.4.2.6, rule_3.4.3.1, rule_3.4.3.2, rule_3.4.3.3, rule_3.4.3.4, rule_3.4.3.5, rule_3.4.3.6, rule_3.4.3.7, rule_3.4.3.8, rule_3.4.4.1.1, rule_3.4.4.1.2, rule_3.4.4.1.3, rule_3.4.4.1.4, rule_3.4.4.1.5, rule_3.4.4.2.1, rule_3.4.4.2.2, rule_3.4.4.2.3, rule_3.4.4.2.4, rule_3.4.4.2.5, rule_3.5, rule_3_4_2_1, rule_3_4_2_2, rule_3_4_2_3, rule_4.1.1.1, rule_4.1.1.2, rule_4.1.1.3, rule_4.1.1.4, rule_4.1.10, rule_4.1.11, rule_4.1.12, rule_4.1.13, rule_4.1.14, rule_4.1.15, rule_4.1.16, rule_4.1.17, rule_4.1.2.1, rule_4.1.2.2, rule_4.1.2.3, rule_4.1.3, rule_4.1.4, rule_4.1.5, rule_4.1.6, rule_4.1.7, rule_4.1.8, rule_4.1.9, rule_4.2.1.1, rule_4.2.1.2, rule_4.2.1.3, rule_4.2.1.4, rule_4.2.1.5, rule_4.2.1.6, rule_4.2.2.1, rule_4.2.2.2, rule_4.2.2.3, rule_4.2.3, rule_4.3, rule_5.1.1, rule_5.1.2, rule_5.1.3, rule_5.1.4, rule_5.1.5, rule_5.1.6, rule_5.1.7, rule_5.1.8, rule_5.2.1, rule_5.2.10, rule_5.2.11, rule_5.2.12, rule_5.2.13, rule_5.2.14, rule_5.2.15, rule_5.2.16, rule_5.2.17, rule_5.2.18, rule_5.2.19, rule_5.2.2, rule_5.2.20, rule_5.2.3, rule_5.2.4, rule_5.2.5, rule_5.2.6, rule_5.2.7, rule_5.2.8, rule_5.2.9, rule_5.3.1, rule_5.3.2, rule_5.3.3, rule_5.4.1, rule_5.4.2, rule_5.4.3, rule_5.4.4, rule_5.5.1.1, rule_5.5.1.2, rule_5.5.1.3, rule_5.5.1.4, rule_5.5.1.5, rule_5.5.2, rule_5.5.3, rule_5.5.4, rule_5.5.5, rule_5.6, rule_5.7, rule_6.1.1, rule_6.1.10, rule_6.1.11, rule_6.1.12, rule_6.1.13, rule_6.1.14, rule_6.1.2, rule_6.1.3, rule_6.1.4, rule_6.1.5, rule_6.1.6, rule_6.1.7, rule_6.1.8, rule_6.1.9, rule_6.2.1, rule_6.2.10, rule_6.2.11, rule_6.2.12, rule_6.2.13, rule_6.2.14, rule_6.2.15, rule_6.2.16, rule_6.2.17, rule_6.2.18, rule_6.2.19, rule_6.2.2, rule_6.2.20, rule_6.2.3, rule_6.2.4, rule_6.2.5, rule_6.2.6, rule_6.2.7, rule_6.2.8, rule_6.2.9, scored, selinux, services, setup_audit, skip_ansible_lint, squashfs, stickybits, sudo, sysctl, udf, vfat, xwindows]

**Comment by uk-bolly** [comment]
Closing issue - Stale
