### ISSUE TITLE
User nobody should be excluded from ownership and uid does not equal gid

### ISSUE THREAD

**Issue by areh** [ansible-lockdown/RHEL8-CIS#148]
**Describe the Issue**
When user nobody (UID 65534) is included in setting ownership the role will manipulate `/` causing severe problems for the target system. Also, there is a variable `rhel8cis_int_gid` being used for comparison with uid. While this works since all newer systems use same gid and uid for normal users it may differ on some systems.

**Expected Behavior**
System should not be rendered unusable by running the role.

**Actual Behavior**
The root folder (/) gets chown to user nobody by the role causing severe problems.

**Environment (please complete the following information):**
 - Ansible Version: 2.9.27
 - Host Python Version: Python 3.6.8
 - Ansible Server Python Version: Python 3.6.8
 - Additional Details:

**Additional Notes**
The proposed solution has been tested and found to work

**Possible Solution**
Introduce two new variables, `rhel8cis_int_uid` and `rhel8cis_int_uid_max`. Set `rhel8cis_int_uid` to be `1000` and `rhel8cis_int_uid_max` to `65533`. Use `rhel8cis_int_uid` when comparing with UIDs, this includes tasks for 6.2.x and templates for 4.1.9, 4.1.10, 4.1.12, 4.1.13 and 4.1.14.
Use `rhel8cis_int_uid_max` to prevent chown on / for user nobody in section 6.2.8. This has been fixed in 6.2.7 using a slightly different approach.

**Comment by uk-bolly** [comment]
Hi @areh 

Thank you for taking the time to highlight this issue and we can see how this may cause problems on running systems. We only test as noted on clean new systems, so this feedback helps to to try and minimise any potential disruption that may occur.
We will look at how this could be adopted aware that it will affect a number of controls and the related auditing components.

regards

uk-bolly

**Comment by uk-bolly** [comment]
Hi @areh 

Thank you again for the feedback.
An update the latest devel branch has now been released and this should address the issues you have seen here.
Please feel free to close the issue if all is working as expected or feedback accordingly.

Thanks again

uk-bolly

**Comment by uk-bolly** [comment]
hi @areh 

Thank you for your patience and the time you take raisin the issues.
I have added this in a slightly different way to the rhel9-cis role. This is the same currently as the rhel8 role but with some alternative ways of doing things. Hopefully speed and logic improvements. In this case a discovery of the IDs takes place or can be overridden in defaults/main
If this works for you i can add this into rhel8-cis role also?

Many thanks 

uk-bolly

**Comment by uk-bolly** [comment]
hi @areh 

I have added this to a new release hoping to be pushed to devel in the next week.
This should resolve the issue you have raised.

regards
uk-bolly

**Comment by georgenalen** [comment]
This was addressed in release 2.1.0
