### ISSUE TITLE
Create Oracle Linux 8 playbook

### ISSUE THREAD

**Issue by adds68** [ansible-lockdown/RHEL8-CIS#150]
**Feature Request or Enhancement**
 - Feature [x]
 - Enhancement []

**Summary of Request**
I've manage to test/run this playbook successfully against an Oracle Linux 8 deployment.

As OL8 is just a re-packaged RHEL8, there is very little difference.

The only tasks i needed to disable were:

- 1.2.1
- 1.2.2

**Describe alternatives you've considered**
Writing custom ansible playbooks for this is truly awful and the ansible-lockdown project is the only logical place i can see this type of work/effort taking place.

**Comment by uk-bolly** [comment]
hi @adds68 

I have spun up an oracle85 server to confirm this is working as expected.
I can see this has skipped 1.2.1 with the current settings and when checking closer using the setup module the system does indeed return OracleLinux

"ansible_distribution": "OracleLinux"

I believe this is working as expected in this instance. If you are seeing something different or these controls are still running can you please provide the ansible and python versions you are running as well as the output of the ansible_distribution from the setup module.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
Closing Issue - Stale
