### ISSUE TITLE
1.4.2 | L1 | PATCH | Ensure filesystem integrity is regularly checked] failed with default value

### ISSUE THREAD

**Issue by bdouxx** [ansible-lockdown/RHEL8-CIS#152]
**Describe the Issue**
in devel and main branch:

TASK [/perso/VM/ansible/RHEL8-CIS : 1.4.2 | L1 | PATCH | Ensure filesystem integrity is regularly checked] ****************************************
fatal: [red-hat-test]: FAILED! => {"changed": false, "msg": "Will not manage /etc/crontab via cron_file, see documentation."}

It's forbiden in ansible/lib/ansible/modules/cron.py
https://github.com/ansible/ansible/blob/601d66c7e51b60781e97e4dcb800a39065c0c98d/lib/ansible/modules/cron.py#L618

**Environment (please complete the following information):**
pip list --verbose
Package      Version Location                                        Installer
------------ ------- ----------------------------------------------- ---------
ansible      5.0.1   /home/bdouxx/venv/lib/python3.9/site-packages pip
ansible-core 2.12.1  /home/bdouxx/venv/lib/python3.9/site-packages pip
cffi         1.15.0  /home/bdouxx/venv/lib/python3.9/site-packages pip
cryptography 36.0.1  /home/bdouxx/venv/lib/python3.9/site-packages pip
graphviz     0.19.1  /home/bdouxx/venv/lib/python3.9/site-packages pip
Jinja2       3.0.3   /home/bdouxx/venv/lib/python3.9/site-packages pip
MarkupSafe   2.0.1   /home/bdouxx/venv/lib/python3.9/site-packages pip
packaging    21.3    /home/bdouxx/venv/lib/python3.9/site-packages pip
pip          21.3.1  /home/bdouxx/venv/lib/python3.9/site-packages pip
pipdeptree   2.2.0   /home/bdouxx/venv/lib/python3.9/site-packages pip
pycparser    2.21    /home/bdouxx/venv/lib/python3.9/site-packages pip
pyparsing    3.0.6   /home/bdouxx/venv/lib/python3.9/site-packages pip
PyYAML       6.0     /home/bdouxx/venv/lib/python3.9/site-packages pip
resolvelib   0.5.4   /home/bdouxx/venv/lib/python3.9/site-packages pip
setuptools   59.6.0  /home/bdouxx/venv/lib/python3.9/site-packages pip
wheel        0.37.0  /home/bdouxx/venv/lib/python3.9/site-packages pip

**Comment by uk-bolly** [comment]
hi @bdouxx 

Thank you for the feedback and taking the time to raise this issue. We can see this only affects later releases of ansible as the module as changed to not allow this change to /etc/crontab.
We have just released an update to the content and we will looking at how best we can approach this going forward while observing the steps as dictated by the benchmark.
We agree this would be good to adopt this better practise way of adding cron entries.

Thanks again

uk-bolly

**Comment by Thulium-Drake** [comment]
I'd suggest that taking the same approach as for modprobe makes sense, all CIS modifications are stored in /etc/modprobe.d/CIS.conf :-)

**Comment by uk-bolly** [comment]
Hi @bdouxx 

Thanks again for raising this issue. Unfortunately as you may have seen we missed the last release to devel and then to main.
I have however had a chance to look into this. 
This control has the ability to change the file in the defaults/main.yml from /etc/crontab (current default) to an alternate location, so should be able to work around the issue.
While we looks to moving more items to templates (as noted by @Thulium-Drake). This should help you to get through by changing that settings.

We are however developing a potential new RHEL9(not yet GA) based off RH8 for this moving more to templates(https://github.com/ansible-lockdown/RHEL9-CIS). 
We are keen to get feedback on this before both the OS and the benchmark are officially released on how we can improve the content. So please feel free to download and test. The corresponding Audit is also available.

I hope that helps?

uk-bolly

**Comment by uk-bolly** [comment]
Closing Issue
