### ISSUE TITLE
Alternative to fail with incompatible OS

### ISSUE THREAD

**Issue by RayMcAdmin** [ansible-lockdown/RHEL8-CIS#155]
**Feature Request**
 - At present, the first task in the role is to assess whether the operating system is RHEL8 and if not, fail. Is there a way around this/is it plausible to simply have the role 'skipped' instead, in the role itself?

**Context**: I am using Ansible as host configuration management within Red hat Satellite. In this scenario, there is no playbook running this role, but instead, a hostgroup which contains a mix of OS has a default set of Ansible roles and simply runs 'all ansible roles' against all hosts. In this scenario, when the OS is correctly evaluated as not being RHEL8, the role fails, failing the job and preventing all other (valid) roles from being applied

**Summary of Request**
Instead of failing when the detected OS is not RHEL8, the role should be skipped

**Describe alternatives you've considered**
In the context of how we're using the role, i'm not sure that there is an alternative to modifying the role

**Suggested Code**
in main.yml, rather than fail, perhaps an 'assert that' task or similar which does the same check, with the result registered and then added as a when criteria on the remaining includes so that the same result is achieved (no additional tasks are run) but the playbook is not 'failed'

**Comment by ccravens** [comment]
I would also like to add my 2 cents. Due to CentOS going EOL we are working to migrate to Amazon Linux 2 and this issue appears to prevent the script from running against AL2 instances.

**Comment by uk-bolly** [comment]
Hi @RayMcAdmin @ccravens 

Thank you both for taking the time to raise this issue and confirmation.
There is a new branch called 0s_checks that should work for you both.
The check has been changed to an assert with a when statement
if os_checks = true and not system_is_ec2 (is the system is AWS hosted)
This should allow you to skip if you don't want to check OR or you are using the system_is_ec2 varaible for AWS systems.

As we are aware CentOS now set to stream this is also tested against both Rocky and AlmaLinux which are picking up where CentOS has left off.
For Amazon Linux - this is not tested and i am sure there are some differences that would need to be worked through.

If you could let me know if this solution works for you i can raise the PR to pull this in.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
Hi @RayMcAdmin @ccravens 

This option now being available, this should get you through the steps you need so you can run where required

With regard to Amazon Linux this a very different benchmark for CIS and doesnt align with other official releases (Watch this space over the next week or so :) ).

Regards

ukbolly

**Comment by uk-bolly** [comment]
Hi @RayMcAdmin @ccravens

We have this week released a specific amazonlinux2 CIS benchmark. This is different from RHEL with different control IDs (as per the benchmark documentation). 
For those who need to adhere to the amazonlinux specific benchmark controls this is the one to choose.

regards
ukbolly

**Comment by ccravens** [comment]
@uk-bolly excellent work thank you for this!
