### ISSUE TITLE
Section 1.1.7.4 - 1.1.7.5

### ISSUE THREAD

**Issue by flwitten** [ansible-lockdown/RHEL8-CIS#179]
**Question**
Shouldn't there be more todo than just adding userquota and groupquota?
According to the CIS Benchmark document following steps are taken:
* add boot option
* remount
* create quota db
* restorecon
* enable quotas

**Environment (please complete the following information):**
 - Ansible Version: core 2.11.10
 - Host Python Version: 3.6.8
 - Ansible Server Python Version: 3.6.8
 - Additional Details:

**Comment by flwitten** [comment]
In addition it seems that the proposed remediation is only valid for ext4 but the default filesystem is xfs.

**Comment by georgenalen** [comment]
Closing this ticket due to being stale
