### ISSUE TITLE
1.4.1 Ensure bootloader password is set | always skipped

### ISSUE THREAD

**Issue by flwitten** [ansible-lockdown/RHEL8-CIS#180]
**Describe the Issue**
Wrong variable used in when condition, as grub_pass only exists in file cis_1.4.x.yml,
this leads to task never being executed.

**Expected Behavior**
Task should be executed not skipped

**Actual Behavior**
Task is skipped

**Control(s) Affected**
1.4.1

**Environment (please complete the following information):**
 - Ansible Version: 2.11
 - Host Python Version: 3.6
 - Ansible Server Python Version: 3.6
 - Additional Details:

**Additional Notes**

**Possible Solution**
password hash is actually defined in variable rhel8cis_bootloader_password_hash

**Comment by uk-bolly** [comment]
hi @flwitten 


Thank you for taking the time to highlight this issue, this is a great improvement.
I am hoping to get the fix out for this week into devel, approaching this in the following way.

- main.yml assertion update - checks for string start and but not the default
1.4.1 - rhel8cis_set_boot_pass is set to true only conditional

Regards uk-bolly

**Comment by georgenalen** [comment]
This was addressed in release 2.1.0
