### ISSUE TITLE
1.8.5 | Ensure automatic mounting of removable media is disabled | Typo

### ISSUE THREAD

**Issue by flwitten** [ansible-lockdown/RHEL8-CIS#181]
**Describe the Issue**
In the "lineinfile"-Module the parameter regex is used instead of regexp

**Expected Behavior**
---

**Actual Behavior**
---

**Control(s) Affected**
1.8.5

**Environment (please complete the following information):**
 - Ansible Version: 2.11
 - Host Python Version: 3.6
 - Ansible Server Python Version: 3.6
 - Additional Details:

**Additional Notes**
---

**Possible Solution**
replace regex with regexp

**Comment by uk-bolly** [comment]
hi @flwitten 

Thank you again for taking the time to raise these issues, feedback like this enables us to improve.
We are hoping to get these issues merged into devel by the end of this week.

regards

uk-bolly

**Comment by georgenalen** [comment]
This was addressed in release 2.1.0
