### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-lockdown/RHEL8-CIS#212]
**Question**
I have come across some issues with the current release of the role. Can you let me know when a new release is planned?

Thanks!

**Comment by uk-bolly** [comment]
hi @Thulium-Drake 

Can we confirm which branch you are referring to? I am assuming devel?

If you have a few to provide is it worth going through them on discord if you are able to?

Thanks as always

uk-bolly

**Comment by Thulium-Drake** [comment]
Sure, I can hop on Discord, do you have a link somewhere? :)

But we're currently running tag 2.0.0 in our environment

**Comment by uk-bolly** [comment]
Hi 

here is the link

https://discord.gg/JFxpSgPFEJ

Thanks 

uk-bolly

**Comment by cf-sewe** [comment]
What is the outcome of that discussion?
I have to admit that I am also unsure what version to use:

- Version releases in [Ansible Galaxy](https://galaxy.ansible.com/mindpointgroup/rhel8_cis)
- Github tag version? (2.0.0)
- or devel branch

It seems both the galaxy and tag version are too outdated. Actually for my environment they dont work due to bugs which have been fixed in devel. But is devel "stable" enough to be used on production?

**Comment by uk-bolly** [comment]
hi @Thulium-Drake and @cf-sewe 

Apologies for the delay in this.  As of this morning, devel is now merged to main (thanks @Thulium-Drake for your testing and feedback). 
A new tagged release should be out for draft tomorrow and galaxy updated to reflect the newest release.

@cf-sewe generally devel is the latest releases with fixes applied etc, this will be a working branch and can change quite regularly. Occasionally this is also the newest updates to the benchmark there is we do aim to release to main a few weeks after devel updates dependant on feedback (this is not always the case unfortunately), there is a discord channel (in the readme)recently opened to assist with this so we can get on top of this a little quicker.
The speed of releases depends very much on client priority and requirements.

Very best and thank you both for your support

uk-bolly

**Comment by Thulium-Drake** [comment]
Maybe add a note to the Branches section in the Readme to cement this in :-) (or rename it to lifecycle or something like that)

That should probably fix issues like these

**Comment by georgenalen** [comment]
With the new release completed I'm closing this ticket. The lifecycle notes will be added into the next minor release
