### ISSUE TITLE
Package discrepency report is too noisy (maybe?)

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-lockdown/RHEL8-CIS#222]
**Describe the Issue**
At the end of a run the following output is collected:

```
rpm -Va --nomtime --nosize --nomd5 --nolinkto
```
This reports a lot of interesting information, however, it also reports files that are changed due to the course of 'natural' system operations, such as:

- Log files
- Default config files (that are either removed or changed)
- /etc/default/ files 
- issue / motd 
- many others

I feel that this creates more noise then it's worth. I'd like to suggest to change this command to the following:

```
rpm -Va --nomtime --nosize --nofiledigest --nolinkto --nomode --noconfig --noghost
```
(--nomd5 was changed to --nofiledigest according to the RPM manpage)

This excludes config files, or files that are not provided by the package, but it does still other issues, such as missing files or broken package dependencies.

**Environment (please complete the following information):**
 - Using branch: 2.1.0
 - Additional Details:

**Comment by Thulium-Drake** [comment]
Durr, I need to read better, the issue still stands, but it only pertains to file _mode_, not content

**Comment by uk-bolly** [comment]
hi @Thulium-Drake 

Thank you for this feedback, explanation and solution. It is a rather strange control asking to alert on items that are changed as part of the benchmark itself. These could be added to an exclusion list so we only get the detail of the actual potential problem packages.
While i feel this would be a great improvement, we are following the CIS controls direction on this. If we were to change this it no longer aligns with the audit they are expecting.
As we work through more of these we do see quite a few improvements similar to this. I will be sure to raise this with the team here at MindPointGroup and see if this is a control we would improve prior to CIS.
Watch this space

Many thanks as always

uk-bolly

**Comment by georgenalen** [comment]
Closing stale issue
