### ISSUE TITLE
Chrony configuration is customized for Debian, not RHEL8

### ISSUE THREAD

**Issue by OscarElits** [ansible-lockdown/RHEL8-CIS#227]
**Describe the Issue**
Paths in templates/chrony.conf.j2 doesn't match paths for RHEL8. Other parameters should also be inspected to make sure they're customized for RHEL8 (https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-chrony_configuring-basic-system-settings).

**Expected Behavior**
Path to `chrony.keys` should be `/etc/chrony.keys`
Path to `chrony.drift` should be `/var/lib/chrony/drift`

**Actual Behavior**
Path to `chrony.keys` is `/etc/chrony/chrony.keys`
Path to `chrony.drift` is `/var/lib/chrony/chrony.drift`

**Control(s) Affected**
2.1.2

**Possible Solution**
* Update paths. 
* Inspect chrony parameters to make sure they're customized for RHEL8 and not Debian

**Comment by uk-bolly** [comment]
hi @OscarElits 

Thank you for taking the time to raise this issue, that is indeed a good find. I believe this has been incorporated into the latest devel branch and should now be resolved?

many thanks

uk-bolly

**Comment by uk-bolly** [comment]
Hi @OscarElits 

You are correct, apologies I was running a different baseline. I will get this followed up as soon as possible.

Thank you

uk-bolly

**Comment by OscarElits** [comment]
No worries. Thank you @uk-bolly
