### ISSUE TITLE
LE_audit_setup - Copy audit binary 

### ISSUE THREAD

**Issue by benbulll** [ansible-lockdown/RHEL8-CIS#228]
**Describe the Issue**
When running the playbook with Audit & local goss copy enabled, the playbook fails due to the source being missing in LE_audit_setup.yml.

**Expected Behavior**
Playbook should find source from "/defaults/main.yml" & copy the local goss binary from the control node to the host node.

**Actual Behavior**
Src is empty & the playbook fails.

**Environment (please complete the following information):**
 - Ansible Version: ansible 2.10.8
 - Host Python Version: Python 3.10.4
 - Ansible Server Python Version:Python 3.10.4
 - Using branch: main
 - Additional Details:

**Additional Notes**
Hi, unless i'm missing something the task "Copy Audit Binary" should get its src from "audit_local_copy" in the /defaults/main.yml, but the src in the task is just blank.

**Possible Solution**
Add audit_local_copy variable to Copy audit binary src.

**Comment by uk-bolly** [comment]
hi @benbulll 

Thank you for raising this issue. It's feedback like this that helps us to improve.You are correct the src is missing. This is also a variable that can be set in a variable override.
copy_goss_from_path
We will be adding this into the latest PR, which should be out this week.

regards

uk-bolly
