### ISSUE TITLE
New release date??

### ISSUE THREAD

**Issue by ozgurgul** [ansible-lockdown/RHEL8-CIS#237]
**Question**
Hi there, when will you be releasing a new version of this repo? I've noticed many brilliant works are done and many PRs are merged but the latest version is from July 6th. Would you please advise?

**Comment by georgenalen** [comment]
Hey @ozgurgul 
 I apologize for the long time between releases, we have been swamped with other projects. I'm finally able to start shifting focus back to this project. I'm starting work on the RHEL8 CIS and I hope to possibly, maybe, hopefully have a release by Wednesday next week. I'll keep dumping updates into devel before the full release into main. 

-George

**Comment by georgenalen** [comment]
@ozgurgul,
 I have all of the changes I hope to get in the new release merged into devel. I'm giving it a bit of time to cook there before cutting an official release. My thought is to have the release on either Friday or Monday if things in devel are still looking good. 

-George

**Comment by uk-bolly** [comment]
hi @ozgurgul 

Apologies for the delay on this, we have had other client priorities which means unfortunately, we didn't get around to release this one.
However we have added alot of new enhancements, issue fixes, workflow piepline updates which will help going forward, these have been in devel for the last 3-4weeks and all looks good so we hope to get a release out the next couple of days.

thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @ozgurgul 

The new release is now avaible. will be synced with galaxy later today. Once again apologies for the delay.

Many thanks

uk-bolly

**Comment by bbaassssiiee** [comment]
```
ansible-galaxy install mindpointgroup.rhel8_cis
```

**Comment by ozgurgul** [comment]
Thanks for sharing.
