### ISSUE TITLE
Unsupported parameters for (ansible.legacy.command) module: warn

### ISSUE THREAD

**Issue by fnschroeder** [ansible-lockdown/RHEL8-CIS#243]
**Issue**
Consistent error when running the list users preliminary task due to task using unsupported parameter. And any that use the builtin command with `warn `as a parameter.

**Expected Behavior**
Control executing without issues

**Actual Behavior**
 rhel8-ami-build.amazon-ebs.rhel8_ami: TASK [rhel-8-lockdown : PRELIM | List users accounts] **************************
 rhel8-ami-build.amazon-ebs.rhel8_ami: fatal: [default]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) **module: warn**. Supported parameters include: stdin, removes, _uses_shell, strip_empty_ends, argv, executable, stdin_add_newline, chdir, creates, _raw_params."}

**Control(s) Affected**

https://github.com/ansible-lockdown/RHEL8-CIS/blob/0220ed104c775b4f82d39fcfad3e098fa98da516/tasks/prelim.yml#L7
https://github.com/ansible-lockdown/RHEL8-CIS/blob/0220ed104c775b4f82d39fcfad3e098fa98da516/tasks/check_prereqs.yml#L10
https://github.com/ansible-lockdown/RHEL8-CIS/blob/0220ed104c775b4f82d39fcfad3e098fa98da516/tasks/section_3/cis_3.1.x.yml#L69

Example:
`- name: "PRELIM | List users accounts"
  command: "awk -F: '{print $1}' /etc/passwd"
  args:
      warn: false
  changed_when: false
  check_mode: false
  register: users`

**Environment:**
 - Ansible Version: 2.14.1
 - Using branch: main

**Additional Notes**
According to:
[https://github.com/ansible/ansible/blob/stable-2.14/changelogs/CHANGELOG-v2.14.rst#removed-features-previously-deprecated](https://github.com/ansible/ansible/blob/stable-2.14/changelogs/CHANGELOG-v2.14.rst#removed-features-previously-deprecated
)
_command/shell - remove deprecated `warn `module param_

**Possible Solution**
This might be a quick fix to just remove the warn parameter

**Comment by jmighion** [comment]
This is also affecting us on ansible 2.14.1, but downgrading to 2.13.7 worked. I did not test the versions in between though.

The commit above looks like it would address the issue.

**Comment by uk-bolly** [comment]
hi @fnschroeder @jmighion 

Thank you for raising this issue, feedback like this helps us to improve.
I am happy to say this is being address in the jan23 release to devel. Hopefully over the next week will be merged.

Regards

uk-bolly

**Comment by uk-bolly** [comment]
> Hello!
> 
> I saw that the fixes for this issue were merged on January 23rd, but the latest published version (2.1.0) does not contain the fix. Do you have any plan to release a new version including all these fixes?

hi @CFSNM 

We want to try and get the update out asap. We have had other client priorities that have taken a precendence (you may have seen alot of updated recently across many repos).
I will see if we can get this out in th enext couple of days into a release.

many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @CFSNM @fnschroeder 

Thank you for your patience, you will find that there has been a number of big lifts in work recently and these are now resolved in the latest release.
I will close this issue , please feel free to raise anything should you come across it.
Once again thank you for your feedback.

uk-bolly
