### ISSUE TITLE
Support for Oracle Linux 8 or Oracle Linux 9

### ISSUE THREAD

**Issue by NeilDavisNPS** [ansible-lockdown/RHEL8-CIS#248]
Would it be possible to extend the supported platforms to Oracle Linux 8  / Oracle Linux 9?
I can add the required file to the vars subdirectory.. however, when running a pipeline which installs this role, editing the file is not possible (due to the pipeline)

**Comment by uk-bolly** [comment]
hi @NeilDavisNPS 

Thank you for raising this question. Feedback is always appreciated.
If you have the values needed, you could fork your own branch and then pull that role in to your pipeline to test. If that works you could then raise a PR to pull into this repository.

Alternatively if you would like further assistance in achieving the above or like to discuss further, you could ask the question on the discord discussions.
https://discord.io/ansible-lockdown
Note this is RHEL8 and we would need to do the same for the rhel9-cis repository.

regards

uk-bolly

**Comment by uk-bolly** [comment]
hi @NeilDavisNPS 

Wondering if you have had a chance to look at this? If this working as expected now?

thanks

uk-bolly

**Comment by NeilDavisNPS** [comment]
Hi,

My sincere apologies.. life has been “hectic”.. and work more so.
I have tested the devel branch for RHEL8-CIS and that continues to work, in that I am able to build out various images for deployment on OCI.

My attempts to validate RHEL9-CIS have been less successful, as one of the pre-execution steps attempts to validate that the root account has a password. Since this is running on an instance in OCI, the root account does not possess a password; ssh access is via public/private keys, and the nominated admin account (opc) has passwordless sudo access.

webserver.oracle-oci.ncs_web_image: TASK [RHEL9-CIS : Ensure root password is set] *********************************
    webserver.oracle-oci.ncs_web_image: task path: /home/ndavis/.ansible/roles/RHEL9-CIS/tasks/main.yml:47
    webserver.oracle-oci.ncs_web_image: fatal: [default]: FAILED! => {"changed": false, "cmd": "passwd -S root | grep \"Password set, SHA512 crypt\"", "delta": "0:00:00.046025", "end": "2023-03-02 14:15:36.706958", "msg": "non-zero return code", "rc": 1, "start": "2023-03-02 14:15:36.660933", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
    webserver.oracle-oci.ncs_web_image:
    webserver.oracle-oci.ncs_web_image: PLAY RECAP *********************************************************************
    webserver.oracle-oci.ncs_web_image: default                    : ok=4    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0


Neil Davis
NEC Software Solutions
Please consider the environment before printing this email

***@***.***

**Comment by uk-bolly** [comment]
hi @NeilDavisNPS 

Not a problem i know exactly how it goes.

It is just the rhel8-cis. If that is working as expected i will add and try to get to testing oracle9 today (will raise the issue there),

Thanks again 

uk-bolly
