### ISSUE TITLE
Some things do not work when rhel8cis_crypto_policy is FUTURE

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-lockdown/RHEL8-CIS#273]
https://github.com/ansible-lockdown/RHEL8-CIS/blob/49117ef490f6d6894804407a5b10ed43f8a68a50/defaults/main.yml#L425

Lot's of repositories and mirrors are signed by Let's Encrypt or GlobalSign, which use 2048 bits keys.

FIPS is a bit more secure than DEFAULT.

**Comment by uk-bolly** [comment]
Hi @bbaassssiiee 

This is very true but fips is not without its own challenges. 
Like all benchmarks it does require the user to understand what impact each control has on their system and the way that it works for them. 
While DEFAULT is not ideal it is still more restrictive than LEGACY. Ideally though it should be greater as you have pointed out.

Thanks as always

uk-bolly

**Comment by Thulium-Drake** [comment]
There's a workaround for that (that's been sitting in my mailbox for over a year now, as I haven't needed it yet) that might be a good fit for in this role somewhere:

```
echo 'key_exchange = ECDHE RSA DHE DHE-RSA PSK DHE-PSK ECDHE-PSK ECDHE-GSS DHE-GSS' > /etc/crypto-policies/policies/modules/RSA-2048.pmod
echo 'min_rsa_size = 2048' >> /etc/crypto-policies/policies/modules/RSA-2048.pmod

update-crypto-policies --set FUTURE:RSA-2048
```

This will allow RSA keys with a length of 2048 bits, but still keep all the other policies in place.

However, I have no clue how useful that is (I don't know the details of the crypto policies, just that setting FUTURE seems to break a lot of things :-) )

**Comment by bbaassssiiee** [comment]
Nice, I used a custom policy:

```properties
# https://access.redhat.com/articles/3642912

mac = AEAD HMAC-SHA2-384

group = X25519 X448 SECP256R1 SECP384R1 SECP521R1 \
    FFDHE-2048 FFDHE-3072 FFDHE-4096 FFDHE-6144 FFDHE-8192

hash = SHA2-256 SHA2-384 SHA2-512 SHA3-256 SHA3-384 SHA3-512 SHA2-224

# SHA1 signatures needed for DNSSec
sign = EDDSA-ED25519 \
       RSA-PSS-SHA2-256 RSA-PSS-SHA2-384 RSA-PSS-SHA2-512 \
       RSA-SHA3-256 RSA-SHA2-256 \
       RSA-SHA3-384 RSA-SHA2-384 \
       RSA-SHA3-512 RSA-SHA2-512 \
       RSA-PSS-SHA2-224 RSA-SHA2-224 \
       ECDSA-SHA1 RSA-PSS-SHA1 RSA-SHA1

# tls_cipher is deprecated
cipher@TLS = AES-256-GCM AES-256-CCM \
    AES-128-GCM AES-128-CCM

cipher = AES-256-GCM AES-256-CCM CHACHA20-POLY1305 \
    CAMELLIA-256-GCM AES-256-CTR AES-128-GCM AES-128-CCM AES-128-CTR

# Yum mirrors need ECDHE (using weak elliptic curves like ecdh-sha2-nistp521)
key_exchange = ECDHE DHE-PSK ECDHE-PSK DHE DHE-RSA PSK DHE-PSK

# protocol is deprecated
protocol@TLS = TLS1.3 TLS1.2 DTLS1.2
# ike_protocol is deprecated
protocol@IKE = IKEv2

min_tls_version = TLS1.2
min_dtls_version = DTLS1.2

# Parameter sizes not ideal, but needed for some repositories
min_dh_size = 2048
min_dsa_size = 2048
min_rsa_size = 2048

# GnuTLS only for now
sha1_in_certs = 0

arbitrary_dh_groups = 1
ssh_certs = 1
ssh_etm = 1
```

**Comment by bbaassssiiee** [comment]
> There's a workaround for that (that's been sitting in my mailbox for over a year now, as I haven't needed it yet) that might be a good fit for in this role somewhere:
> 
> ```
> echo 'key_exchange = ECDHE RSA DHE DHE-RSA PSK DHE-PSK ECDHE-PSK ECDHE-GSS DHE-GSS' > /etc/crypto-policies/policies/modules/RSA-2048.pmod
> echo 'min_rsa_size = 2048' >> /etc/crypto-policies/policies/modules/RSA-2048.pmod
> 
> update-crypto-policies --set FUTURE:RSA-2048
> ```
> 
> This will allow RSA keys with a length of 2048 bits, but still keep all the other policies in place.
> 
> However, I have no clue how useful that is (I don't know the details of the crypto policies, just that setting FUTURE seems to break a lot of things :-) )

This can be implemented since https://github.com/ansible-lockdown/RHEL8-CIS/pull/297 was merged.

**Comment by bbaassssiiee** [comment]
The 3.0.0 version of the benchmark states:

```
Over-riding or opting out of the system-wide crypto policy could allow for
 the use of less secure Ciphers, MACs, KexAlgorithms and GSSAPIKexAlgorithm

Note: If changes to the system-wide crypto policy are required to meet local 
site policy for the openSSH server, these changes should be done with a sub-policy 
assigned to the system-wide crypto policy. For additional information see the 
CRYPTO-POLICIES(7) man page
```

**Comment by uk-bolly** [comment]
hi @bbaassssiiee 

Im hoping that this has now been addressed?
Please feel free to close if this is the case.

Many thanks as always

uk-bolly

**Comment by bbaassssiiee** [comment]
> hi @bbaassssiiee
> 
> Im hoping that this has now been addressed? Please feel free to close if this is the case.
> 

I think we can close this if you move `rhel8cis_allowed_crypto_policies_modules` from vars to defaults, then sites can define their local policy modifications.

**Comment by bbaassssiiee** [comment]
# A PMOD for better SSH security
```
# message authentication code algorithms
mac@SSH = -*-64* -UMAC-128 -HMAC-SHA1
# Encrypt then MAC. Prioritize the etm over the non-etm macs
ssh_etm = 1

# key exchange algorithms
# disables weak DH groups and NIST curves
group@SSH = +X25519 +X448 -FFDHE-2048 -SECP256R1 -SECP384R1 -SECP521R1
# Disable diffie-hellman-group-exchange-sha256
arbitrary_dh_groups = 0

hash@SSH = -SHA1
sign@SSH = -*-SHA1 +EDDSA-ED25519
min_rsa_size = 2048
min_dh_size = {{ min_dh_size }}

# encryption algorithms (ciphers)
cipher@SSH = -*-CBC -CHACHA20-POLY1305 -AES-128-*
ssh_certs = 1
```
