### ISSUE TITLE
rhel8cis_rule_3_3_9 is skipped when ipv6 is not required

### ISSUE THREAD

**Issue by Crayeth** [ansible-lockdown/RHEL8-CIS#278]
**Describe the Issue**
`rhel8cis_rule_3_3_9` is skipped when `rhel8cis_ipv6_required: false`  
But I want to disable ipv6 router advertisements when not using ipv6.  
Because of the _when_ this doesn't seem possible?

**Expected Behavior**
I want to disable ipv6 and also enforce rule 3.3.9

**Actual Behavior**
By disabling ipv6, rule 3.3.9 is skipped.

**Control(s) Affected**
rhel8 cis rule 3.3.9

**Environment:**
 - Ansible Version: [2.13.6] 
 - Host Python Version: [3.10.11]
 - Ansible Server Python Version: [3.6.8]
 - Using branch: [2.2.1]

**Possible Solution**
remove 
```yaml
  when:
      - rhel8cis_ipv6_required
```
or provide another way of enabling/forcing rule 3.3.9 to be executed when `rhel8cis_ipv6_required: false`

**Comment by uk-bolly** [comment]
hi @Crayeth 

Thank you for this issue. I have looked at this and hopefully found a suitable alternative. This is a new setting ```rhel8cis_ipv6_sysctl_force```
if set to true (default) will force these to be set even with ipv6 turnoff.

Hoping to get this and a couple of other merged into devel the next couple of days.

I hope that covers off your requirements.

Thanks again

uk-bolly

**Comment by uk-bolly** [comment]
hi @Crayeth 

This issue has been merged into main. I will therefore close this issue. Please open an issue if you feel this is not resolved.

many thanks

uk-bolly
