### ISSUE TITLE
CIS-CAT-PRO finding 5.4.2

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-lockdown/RHEL8-CIS#284]
**Describe the Issue**
Ensure authselect includes with-faillock.

Description:

The pam_faillock.so module maintains a list of failed authentication attempts per user during a specified interval and locks the account in case there were more than deny consecutive failed authentications. It stores the failure records into per-user files in the tally directory

Locking out user IDs after n unsuccessful consecutive login attempts mitigates brute force password attacks against your systems.

Run the following commands to include the with-faillock option to the current authselect profile:

```bash
# authselect enable-feature with-faillock
# authselect apply-changes 
```

**Expected Behavior**
CIS-CAT-PRO test passes 5.4.2

**Actual Behavior**
CIS-CAT-PRO test fails 5.4.2

**Control(s) Affected**
What controls are being affected by the issue? CIS 5.4.2

**Environment (please complete the following information):

    Ansible Version: [core 2.11.12]
    Host Python Version: [Python 3.6.8]
    Ansible Server Python Version: [Python 3.6.8]
    Using branch: [release 2.2.1]
    Additional Details:

**Additional Notes
CIS-CAT_PRO is the official audit tool for CIS members.

**Possible Solution**
password-auth:

```jinja2
#%PAM-1.0
{{ ansible_managed | comment }}
{{ "Generated in role '%s'" | format(role_name) | comment }}
auth        required      pam_env.so
auth        required      pam_faildelay.so delay=2000000
auth        required      pam_faillock.so preauth silent
auth        sufficient    pam_unix.so
auth        required      pam_faillock.so authfail
auth        required      pam_deny.so

account     required      pam_faillock.so
account     required      pam_unix.so

password    requisite     pam_pwquality.so try_first_pass retry=3 local_users_only authtok_type=
password    sufficient    pam_unix.so try_first_pass use_authtok sha512 shadow
password    required      pam_deny.so
password   required pam_pwquality.so
password required pam_pwhistory.so use_authtok remember=5

session     optional      pam_keyinit.so revoke
session     required      pam_limits.so
-session     optional      pam_systemd.so
session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
session     required      pam_unix.so
```

system-auth:
```jinja2
#%PAM-1.0
{{ ansible_managed | comment }}
{{ "Generated in role '%s'" | format(role_name) | comment }}
auth        required      pam_env.so
auth        required      pam_faildelay.so delay=2000000
auth        required      pam_faillock.so preauth silent
auth        sufficient    pam_unix.so
auth        required      pam_faillock.so authfail
auth        required      pam_deny.so

account     required      pam_faillock.so
account     required      pam_unix.so

password    requisite     pam_pwquality.so try_first_pass retry=3 local_users_only authtok_type=
password    sufficient    pam_unix.so try_first_pass remember=5 use_authtok sha512 shadow
password    required      pam_deny.so
password    required      pam_pwquality.so
password    required      pam_pwhistory.so remember=5 use_authtok

session     optional      pam_keyinit.so revoke
session     required      pam_limits.so
-session     optional      pam_systemd.so
session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
session     required      pam_unix.so

```

**Comment by uk-bolly** [comment]
hi @bbaassssiiee 

This issue has been merged into main. I will therefore close this issue. Please open an issue if you feel this is not resolved.

many thanks

uk-bolly
