### ISSUE TITLE
New style 4.2.3 ensure permission task takes ages

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-lockdown/RHEL8-CIS#286]
**Describe the Issue**
With version 2.2.0 of the role the task for control 4.2.3 was reworked into a 'regular' loop from a command, which increased the runtime for this task massively.

I can't share logs from this environment (I don't have Internet on it), but this task took more then 25 minutes on a production server (Red Hat IdM replica) on which I deployed this version of the role (it's still running... :-/ )

EDIT2: It took 32m52s :sweat_smile:  

EDIT: I did some digging, the find task before it found nearly 3000 files it wanted to check, that might be an excessive exception, but as this was 'just a random' system, I think this will be a problem moving forward.

**Expected Behavior**
Not to take absolute ages

**Actual Behavior**
A clear and concise description of what's happening.

**Control(s) Affected**
What controls are being affected by the issue
4.2.3
**Environment (please complete the following information):**
 - Ansible Version: 2.13.3
 - Host Python Version: 3.6.8
 - Ansible Server Python Version: 3.9.13
 - Using branch: 2.2.1
 - Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
Revert to the shell/command task

**Comment by uk-bolly** [comment]
hi @Thulium-Drake 

This issue has been merged into main. I will therefore close this issue. Please open an issue if you feel this is not resolved.

many thanks

uk-bolly
