### ISSUE TITLE
You need to install "jmespath" prior to running json_query filter.

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-lockdown/RHEL8-CIS#294]
I ran into this error for this task when running an `ansible_local` provisioner as root in Packer:

https://github.com/ansible-lockdown/RHEL8-CIS/blob/d18c4e80f1ea4e64185490598a277f22d34adf7b/tasks/section_6/cis_6.1.x.yml#L328

```
6.1.14 | AUDIT | Audit SUID executables |  Alert SUID executables exist...:   
127.0.0.1 failed: {"msg": "You need to install \"jmespath\" prior to running json_query filter" }
```

Using ansible_python_interpreter=/usr/libexec/platform-python and `yum install python3-jmespath` did not solve the issue. I'm using AlmaLinux 8.7. 
Before running ansible locally in the VM I ran a script to install the ansible-core RPM, and ran a pip3 install jmespath.

**Comment by bbaassssiiee** [comment]
Up until the release of AlmaLinux 8.8 that script worked because pip3 was installed as a weak dependency:
![py39](https://github.com/ansible-lockdown/RHEL8-CIS/assets/10671559/f3927b3d-0991-461c-86dd-c91f2714dfd8)

**Comment by bbaassssiiee** [comment]
https://www.redhat.com/sysadmin/install-python-pip-linux

**Comment by uk-bolly** [comment]
hi @bbaassssiiee 

Thank you for raising this issue and the through investigation into why and how. These details really help.

Think the best thing here to do while the distributors get some consistency is to add this to the FAQs and suggest that the system is patched and jmespath is confirmed prior to running the benchmark remediation.
I have looked at running with JQ that is another product that may not be present on a system but it also comes with a risk if query not closed correctly may affect a system which we would rather not introduce anything at this time that may cause other issues.
Issue raised on RTD to get updated

Thanks as always 

uk-bolly

**Comment by bbaassssiiee** [comment]
Using the local provisioner in Packer I can use this playbook:

```yaml
﻿﻿- name: Play to harden AlmaLinux
  hosts: all:!localhost
  gather_facts: false
  become: true

  pre_tasks:
    - name: Install pip3.11
      ansible.builtin.package:
        name: python3.11-pip
        state: present

    - name: Install jmespath
      ansible.builtin.pip:
       name: jmespath
       state: present
       executable: /usr/bin/pip3.11

  roles:
    - role: rhel8cis
﻿﻿```
