### ISSUE TITLE
IPv6 on localhost important

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-lockdown/RHEL8-CIS#299]
https://github.com/ansible-lockdown/RHEL8-CIS/blob/a0d2d830bb07c0a1ca5e1aaeb297ae180f1e5296/tasks/section_3/cis_3.1.x.yml#L16

[Red Hat's solution 8709](https://access.redhat.com/solutions/8709#rhel89disable) to disable IPv6 mentions

> \# By default, we do not disable IPv6 on localhost, as it's important for multiple
> \# components.  If you want to disable it anyway, change the following
> \# value to 1.
> net.ipv6.conf.lo.disable_ipv6 = 0

Feature request: make IPv6 on localhost a separate config item.

**Comment by bbaassssiiee** [comment]
Yet even after disabling ipv6 alltogether with this role I still see:

```bash
[root@vm]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:c0:ff:ee:c0:de brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.3/24 brd 192.168.1.255 scope global dynamic noprefixroute eth0
       valid_lft 796576sec preferred_lft 796576sec

[root@vm]# ss -tln
State        Recv-Q        Send-Q               Local Address:Port               Peer Address:Port       Process
LISTEN       0             128                        0.0.0.0:22                      0.0.0.0:*
LISTEN       0             128                           [::]:22                         [::]:*
```

There is no `inet6` address, yet ssh seems to listen??

Adding this line to `/etc/ssh/sshd_config` will drop that socket listener:

```kv
AddressFamily inet
```

**Comment by uk-bolly** [comment]
@bbaassssiiee 

Thank you as always, i have added an optional setting in prelim for the June23_updates branch to set sshd accordingly if rhel8cis_ipv6_disable_sshd_inet6 and not rhel8cis_ipv6_required

Feel free to take a quick look an d see if that works.

Cheers

uk-bolly

**Comment by bbaassssiiee** [comment]
I think rhel8cis_ipv6_required is irrelevant, I see rhel8cis_ipv6_disable_sshd_inet6 as a defense in depth measure.

The main issue is that IPv6 on localhost is important to multiple components according to Red Hat, so that deserves a variable too.

**Comment by bbaassssiiee** [comment]
If you disable IPv6 on localhost, take care to remove or comment this entry in `/etc/hosts`:

```
::1         localhost
```

**Comment by bbaassssiiee** [comment]
Thanks
