### ISSUE TITLE
5.6.3 Ensure default user shell timeout is 900 seconds or less

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-lockdown/RHEL8-CIS#310]
While 600 is less than 900, it is an arbitrary choice. Rather use the limit of 900.

https://github.com/ansible-lockdown/RHEL8-CIS/blob/6401b1b151d30092a945d5e9fb992be6bc4fb540/defaults/main.yml#L670

**Comment by uk-bolly** [comment]
hi @bbaassssiiee 

This issue has been merged into main. I will therefore close this issue. Please open an issue if you feel this is not resolved.

many thanks

uk-bolly
