### ISSUE TITLE
CIS Red Hat Enterprise Linux 8 Benchmark v3.0.0

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-lockdown/RHEL8-CIS#324]
## Feature Request or Enhancement

- Feature []

**Summary of Request**
The DRAFT CIS Red Hat Enterprise Linux 8 Benchmark v3.0.0 is available for download and review

This consensus period is scheduled to close on 19 October 2023, pending any new comments and open tickets.

**Comment by bbaassssiiee** [comment]
- disable mounting of freevxfs in /etc/modprobe.d/freevxfs.conf, and likewise: hfs, hfsplus, jffs2

**Comment by bbaassssiiee** [comment]
Only /dev/shm and /tmp should be separate partitions.

**Comment by uk-bolly** [comment]
Hi
Im just finishing off V3 this week, it has taken almost a complete rewrite, due to all the changes. At the same time i have updates the audit as well.
This will be in pre-release to subscribers before releasing to the community in approx 3 months.
Thanks

uk-bolly

**Comment by toddtherod** [comment]
> This will be in pre-release to subscribers before releasing to the community in approx 3 months.

I'm also interested ...What is involved in becoming a subscriber?  Which git repo tag/branch is used for this V3 pre-release version? 
Thanks

**Comment by uk-bolly** [comment]
> > This will be in pre-release to subscribers before releasing to the community in approx 3 months.
> 
> I'm also interested ...What is involved in becoming a subscriber? Which git repo tag/branch is used for this V3 pre-release version? Thanks

hi @toddtherod 

The latest release remediation code is in a restricted repo currently only available to subscribers to lockdown enterprise. While the audit code is available now in the public repo.
There is more information about the subscription at https://lockdownenterprise.com.
I hope that helps, if you have any questions feel free to ask here or join the discord community and find out more.

[Discord Server](https://www.lockdownenterprise.com/discord)

thanks

uk-bolly

**Comment by bbaassssiiee** [comment]
I'm testing the devel branch since 3.0.0 was merged by 
https://github.com/ansible-lockdown/RHEL8-CIS/pull/351

**Comment by bbaassssiiee** [comment]
Raising a few eyebrows...
