### ISSUE TITLE
Generating new GRUB file

### ISSUE THREAD

**Issue by mickey1928geo** [ansible-lockdown/RHEL8-CIS#33]
Vanilla load/test - keep getting this error, and I'm not sure where to go next:

*
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stat'\n\nThe error appears to be in '/etc/ansible/roles/RHEL8-CIS/handlers/main.yml': line 38, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: generate new grub config\n  ^ here\n"}

**Comment by georgenalen** [comment]
Hello,
 We made updates to many of the controls and I think we have a fix to address what you were seeing. If you can run the version from the devel branch again and let me know I can either close this issue or address it if it's still reaming. 


-George

**Comment by mrampant-nist** [comment]
Hello, I am getting this error as well on a UEFI based version.
Running on devel branch:
RUNNING HANDLER [RHEL8-CIS : grub2cfg] ************************************************************************************************************************
fatal: [tournesol]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'lnk_source'\n\nThe error appears to be in '/Users/Mat/.ansible/roles/RHEL8-CIS/handlers/main.yml': line 84, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: grub2cfg\n  ^ here\n"}
...ignoring

**Comment by uk-bolly** [comment]
Thanks @mrampant-nist and @mickey1928geo 

I have added a new fix for this today, that will be pushed up into devel soon.

uk-bolly

**Comment by uk-bolly** [comment]
closing issue merged 7th May - no further information received
