### ISSUE TITLE
Enable setting run_heavy_tests as variable

### ISSUE THREAD

**Issue by aaosopra** [ansible-lockdown/RHEL8-CIS#338]
## Feature Request or Enhancement

- Feature [Enable setting run_heavy_tests as variable]
- Enhancement [Since run_heavy_tests is true in jinja template, you cannot change it without editing the role itself]

**Summary of Request**
run_heavy_tests: {{ run_heavy_tests | default('true') }}

**Describe Alternatives You've Considered**
N/A

**Suggested Code**
run_heavy_tests: {{ run_heavy_tests | default('true') }}

**Comment by uk-bolly** [comment]
hi @aaosopra

Apologies for the delay, i have merged many of your Issues into devel or main now. v3.0.0 is now also released into devel

Many thanks for you help

uk-bolly
