### ISSUE TITLE
RHEL8-CIS-March_24_v3 : Ensure root password is set

### ISSUE THREAD

**Issue by txsastre** [ansible-lockdown/RHEL8-CIS#357]
Testing the playbook with 

/defaults/main.yml

# Only run Audit do not remediate
audit_only: true
# As part of audit_only
# This will enable files to be copied back to control node
fetch_audit_files: true
# Path to copy the files to will create dir structure
audit_capture_files_dir: /home/hal/ansible/hardening/log

First time I changed the password with a 14 length with capital letters, numbers and special characters, but still receiving the same error.

* the client is an Oracle Linux 8.9
* ansible-playbook --version
ansible-playbook [core 2.16.3]
  config file = None
  configured module search path = ['/home/hal/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/hal/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/hal/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.11.8 (main, Feb  7 2024, 21:52:08) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

* OS ansible controller = Debian 12

TASK [/home/hal/ansible/hardening/RHEL8-CIS-March_24_v3 : Ensure root password is set] *********************************************************************
fatal: [SRV3-OL8]: FAILED! => {
    "assertion": "root_passwd_set.rc == 0",
    "changed": false,
    "evaluated_to": false,
    "msg": "You have rule 4.5.2.4 enabled this requires that you have a root password set"
}

**Comment by txsastre** [comment]
Found the problem.
The problem was the Language
I already have "bugs" with RHEL 8 and 9 due to the language chosen, so in .bashrc I added "export LANG=C.UTF-8" in the Ansible user, and now it works perfect.

Indeed, I tend to do that in all users to avoid problems in CLI.

**Comment by uk-bolly** [comment]
Closing as resolved after discussions on discord
