### ISSUE TITLE
Spelling Corrections and variable name update

### ISSUE THREAD

**Issue by msachikanta** [ansible-lockdown/RHEL8-CIS#373]
**Spelling corection**

There are few spelling corrections needed in following files:

tasks --> prelimyml file, line number 183
tasks --> section_4 --> cis_4.3.x.yml, linumber 67

The `files\etc\systemd\system\tmp.mount.j2` file needs to be updated with correct variable names.

**Expected Behavior**

It supposed to be appearing as:

tasks --> prelimyml file, line number 183
`register: discovered_sudoers_files`

tasks --> section_4 --> cis_4.3.x.yml, linumber 67
`loop: "{{ discovered_sudoers_files.stdout_lines }}"`

files\etc\systemd\system\tmp.mount.j2
`Options=mode=1777,strictatime,{% if rhel8cis_rule_1_1_2_1_2 %}nodev,{% endif %}{% if rhel8cis_rule_1_1_2_1_3 %}nosuid,{% endif %}{% if rhel8cis_rule_1_1_2_1_4 %}noexec{% endif %}`

**Actual Behavior**

Currently its appearing as:

tasks --> prelimyml file, line number 183
`register: discovered_sudoers_filess`

tasks --> section_4 --> cis_4.3.x.yml, linumber 67
`loop: "{{ discovered_sudoers_filess.stdout_lines }}"`

files\etc\systemd\system\tmp.mount.j2
`Options=mode=1777,strictatime,{% if rhel8cis_rule_1_1_2_2 %}nodev,{% endif %}{% if rhel8cis_rule_1_1_2_4 %}nosuid,{% endif %}{% if rhel8cis_rule_1_1_2_3 %}noexec{% endif %}`

**Environment (please complete the following information):**

- branch being used: [devel]

**Possible Solution**

Correcting the spellings and renaming the variables in tmp.mount.j2 file will fix the above issues.

**Comment by uk-bolly** [comment]
hi @msachikanta

Thank you for raising this issue, i'm looking and putting a few fixes together and submitting the PR shortly.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @msachikanta 

Consider it done :)
thank you and great spot.


uk-bolly
