### ISSUE TITLE
Error in Pre Audit | Capture pre-audit result]

### ISSUE THREAD

**Issue by txsastre** [ansible-lockdown/RHEL8-CIS#378]
**Describe the Issue**
erro when running playbook to do an audit against a Rocky Linux 8

**Expected Behavior**
to finish correctly and generate a report

**Actual Behavior**
it stops and does not continue

`fatal: [X-OL-8]: FAILED! => {"msg": "the field 'args' has an invalid value ({'pre_audit_summary': '{{ discovered_pre_audit.stdout | from_json | json_query(summary) }}'}), and could not be converted to an dict.The error was: Expecting value: line 1 column 1 (char 0)\n\nThe error appears to be in '/home/hal/ansible/hardening/**RHEL8-CIS/tasks/pre_remediation_audit.yml**': line 98, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n      - name: Pre Audit | Capture pre-audit result\n        ^ here\n"}`

**Control(s) Affected**
What controls are being affected by the issue

**Environment (please complete the following information):**

- latest version Devel
- Ansible Version: ansible [core 2.16.3]
- Host Python Version: Python 3.11.8
- Ansible Server Python Version: Python 3.6.8
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
I think I found it, the problem is when you ask for a report in JSON structure, I tried "document" and it has worked

**Comment by txsastre** [comment]
Tried with document as explained, it does no crash, but it leaves this inside the document

"Error: could not read json data in /home/hal/ansible/hardening/log/RHEL8-CIS-Audit/section_1/cis_1.1/cis_1.1.10.yml: template: test:2:13: executing$""

**Comment by txsastre** [comment]
as I can see in defautls/main.yml 
# Section 1 rules
rhel8cis_rule_1_1_1_1: true
rhel8cis_rule_1_1_1_2: true
rhel8cis_rule_1_1_1_3: true
rhel8cis_rule_1_1_1_4: true
rhel8cis_rule_1_1_1_5: true
rhel8cis_rule_1_1_1_6: true
rhel8cis_rule_1_1_1_7: true
rhel8cis_rule_1_1_1_8: true

there is no rule_1_1_10

**Comment by uk-bolly** [comment]
This has been resolved after discussions on discord. There was an issue with teh way the content was being downloaded
