### ISSUE TITLE
v3.0.0 needs a tweak to run on RHEL

### ISSUE THREAD

**Issue by NeilDavisNPS** [ansible-lockdown/RHEL8-CIS#398]
In v3.0.0, there is now a check (1.2.2-1.2.3) to set  repo_gpgcheck=1  in /etc/dnf/dnf.conf
RedHat (https://access.redhat.com/solutions/7019126) say they do not support this and the default is  0 (disabled)
The question is , should this be disabled on a per use basis, or should it be disabled by the role if it is running on RHEL??

**Environment (please complete the following information):**

- Ansible Version: [2.16.8]
- Host Python Version: [Python 3.11.2]
- Ansible Server Python Version: [3.6.8]
- Setting these for the role allows the role to run to success.
-    # RHEL does not allow gpg in repo
      rhel8cis_rule_1_2_2: false
      # RHEL does not allow gpg in repo
      rhel8cis_rule_1_2_3: false

**Comment by uk-bolly** [comment]
hi @NeilDavisNPS 

Great question, we are aware that Redhat doesn't support repo_gpgcheck for its default public repos as with all baselines it is a a matter of trial and error. So we set each control as being required as per the baseline with the community supporting their own configurations (those with support we would advise differently).
Some users have different ways of patching where that maybe a requirement for their environment and the repos that they use.
If using default redhat repos then it it unlikely to work, so you have made the correct judgement and in most cases an exception would be raised for the auditor to explain why you that control is not actioned. In this case each package is GPG checked still (if using those controls) could be a good way of stating mitigation of the control.

Your suggestion is the way i would do it personally.

i hope that helps.

uk-bolly

**Comment by NeilDavisNPS** [comment]
> hi @NeilDavisNPS
> 
> Great question, we are aware that Redhat doesn't support repo_gpgcheck for its default public repos as with all baselines it is a a matter of trial and error. So we set each control as being required as per the baseline with the community supporting their own configurations (those with support we would advise differently). Some users have different ways of patching where that maybe a requirement for their environment and the repos that they use. If using default redhat repos then it it unlikely to work, so you have made the correct judgement and in most cases an exception would be raised for the auditor to explain why you that control is not actioned. In this case each package is GPG checked still (if using those controls) could be a good way of stating mitigation of the control.
> 
> Your suggestion is the way i would do it personally.
> 
> i hope that helps.
> 
> uk-bolly

That is  sensible.. I'd not considered your point about environment specific requirements. I'll document my playbook accordingly. 

Thanks.

**Comment by bbaassssiiee** [comment]
`repo_gpgcheck==1` did break several times, and worked sometimes. For reliability reasons of patching, I set it to 0 nowadays.

**Comment by uk-bolly** [comment]
hi @NeilDavisNPS 

Thank you again for your time regarding this issue. You should find that this fix was merged into devel and is now in the main branch. I will close this issue, please feel free to reopen if this is not resolved as expected.

Many thanks

uk-bolly

**Comment by NeilDavisNPS** [comment]
> hi @NeilDavisNPS
> 
> Thank you again for your time regarding this issue. You should find that this fix was merged into devel and is now in the main branch. I will close this issue, please feel free to reopen if this is not resolved as expected.
> 
> Many thanks
> 
> uk-bolly

Hi,  whilst my contribution is minimal, I do appreciate the follow up! 
Thank you.
