### ISSUE TITLE
tags for indivual rules are not honored

### ISSUE THREAD

**Issue by dirkvdplas** [ansible-lockdown/RHEL8-CIS#400]
**Describe the Issue**
I tried  to use the role with the following tags, in order to limit the run to specific rules
`rhel8cis_rule_4_4_3_2_1,rhel8cis_rule_4_4_3_2_2,rhel8cis_rule_4_4_3_2_3,rhel8cis_rule_4_4_3_2_4,rhel8cis_rule_4_4_3_2_5,rhel8cis_rule_4_4_3_2_6,rhel8cis_rule_4_4_3_2_7,rhel8cis_rule_4_4_3_3_1,rhel8cis_rule_4_4_3_3_2,rhel8cis_rule_4_4_3_3_3`

I think the issue is caused by a conflict between the section and rule tags. In order for any section4 rule to be execute the tag rhel8cis_section4 has to be used.  But when using the rhel8cis_section4 tags the effect is that ALL rules in section 4 are executed (instead of only the ones specified)
`
# roles/RHEL8-CIS/tasks/main.yml:
- name: Run Section 4 tasks
  when:
      - rhel8cis_section4
  tags:
      - rhel8cis_section4
  ansible.builtin.import_tasks:
      file: section_4/main.yml
`

**Expected Behavior**
I expect that only tasks tagged with the specified rules are being executed

**Actual Behavior**
None of the rules are executed

**Control(s) Affected**
What controls are being affected by the issue

**Environment (please complete the following information):**

- branch being used: [e.g. master]
- Ansible Version: 2.15.1
- Host Python Version: 3.6.8
- Ansible Server Python Version: 3.11.4

**Comment by uk-bolly** [comment]
hi @dirkvdplas 

Thank you for taking the time to raise the issue, this is a great catch. Thank you for raising it.
Hoping to get fixes out this week and merged to devel.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @dirkvdplas 

Thank you again for your time regarding this issue. You should find that this fix was merged into devel and is now in the main branch. I will close this issue, please feel free to reopen if this is not resolved as expected.

Many thanks

uk-bolly
