### ISSUE TITLE
'failed_when' variable incorrect for item 4.4.2.5

### ISSUE THREAD

**Issue by devallan** [ansible-lockdown/RHEL8-CIS#403]
The 'failed_when' check for item 4.4.2.5 is currently "failed_when: rhel8cis_authselect_pam_unix.rc not in [ 0, 1 ]", but the variable rhel8cis_authselect_pam_unix doesn't seem to be defined anywhere and generates an error when I run the code.

The item registers the variable "discovered_authselect_pam_unix", which, I think, is the variable that should be checked.

I suggest changing this:

      - name: "4.4.2.5 | AUDIT | Ensure pam_unix module is enabled"
        ansible.builtin.shell: |
            grep -P -- '\b(pam_unix\.so)\b' /etc/authselect/"$(head -1 /etc/authselect/authselect.conf)"/{system,password}-auth
        changed_when: false
        **failed_when: rhel8cis_authselect_pam_unix.rc not in [ 0, 1 ]**
        register: discovered_authselect_pam_unix

into this:

      - name: "4.4.2.5 | AUDIT | Ensure pam_unix module is enabled"
        ansible.builtin.shell: |
            grep -P -- '\b(pam_unix\.so)\b' /etc/authselect/"$(head -1 /etc/authselect/authselect.conf)"/{system,password}-auth
        changed_when: false
        **failed_when: discovered_authselect_pam_unix.rc not in [ 0, 1 ]**
        register: discovered_authselect_pam_unix

**Comment by uk-bolly** [comment]
hi @devallan 

I will close this issue, please feel free to reopen if this is still an issue.

many thanks

uk-bolly
