### ISSUE TITLE
Error in : RHEL8-CIS: 6.2.9 | PATCH | Ensure root is the only UID 0 account] 

### ISSUE THREAD

**Issue by txsastre** [ansible-lockdown/RHEL8-CIS#408]
**Describe the Issue**
when doing de audit to rhel 8 (oracle linux 8)

TASK [/home/aemer/ansible/hardening/RHEL8-CIS : 6.2.9 | PATCH | Ensure root is the only UID 0 account] *****************
fatal: [RL8-1]: FAILED! => {"msg": "'dict object' has no attribute 'stdout_lines'. 'dict object' has no attribute 'stdout_lines'"}

**Expected Behavior**
to finish the audit

**Actual Behavior**
it stops with an error

**Control(s) Affected**
What controls are being affected by the issue

**Environment (please complete the following information):**

- branch being used: [e.g. devel]
- devel
- Ansible Version: [e.g. 2.10]
ansible [core 2.16.3]
- Host Python Version: [e.g. Python 3.7.6]
3.12
- Ansible Server Python Version: [e.g. Python 3.7.6]
3.12
- Additional Details:

**Comment by txsastre** [comment]
It doesn't matter if I set that value to "true" or "false" always fail.

**Comment by uk-bolly** [comment]
hi @txsastre 

Thank you for raising this issue, working on this now.

kindest regards

uk-bolly

**Comment by uk-bolly** [comment]
hi @txsastre 

I believe this is now resolved and is in the latest release.  Please let me know if you are still seeing issues.

many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @txsastre 

I will close this issue, please feel free to reopen if this is still an issue.

many thanks

uk-bolly
