### ISSUE TITLE
Typo in 2.2.17

### ISSUE THREAD

**Issue by enx-roy-scheepers** [ansible-lockdown/RHEL8-CIS#418]
**Describe the Issue**
when doing de audit to rhel 8 with squid installed

TASK [--: 2.2.17 | PATCH | Ensure web proxy server services are not in use | Remove package] ***
fatal: [server: FAILED! => {"msg": "The conditional check 'rhel8cis_rule_2_217' failed. The error was: error while evaluating conditional (rhel8cis_rule_2_217): 'rhel8cis_rule_2_217' is undefined. 'rhel8cis_rule_2_217' is undefined\n\nThe error appears to be in '/etc/ansible/roles/enx_rhel8_cis/tasks/section_2/cis_2.2.x.yml': line 563, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n      - name: \"2.2.17 | PATCH | Ensure web proxy server services are not in use | Remove package\"\n        ^ here\n"}

**Expected Behavior**
pass this rule

**Actual Behavior**
it stops with an error

Control(s) Affected
What controls are being affected by the issue

Environment (please complete the following information):

    branch being used: [e.g. devel]
    devel
    Ansible Version: [e.g. 2.10]
    ansible [core 2.15]
    Host Python Version: [e.g. Python 3.7.6]
    3.10
    Ansible Server Python Version: [e.g. Python 3.7.6]
    3.10

**Additional Details:**

offending line:  https://github.com/ansible-lockdown/RHEL8-CIS/blob/241557565deed3b92008a6102c7929e4a47a5df8/tasks/section_2/cis_2.2.x.yml#L552

`rhel8cis_rule_2_217` --> `rhel8cis_rule_2_2_17`

**Comment by uk-bolly** [comment]
hi @enx-roy-scheepers 

Many thanks for this finding and subsequent PR. This has been merged.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
Merged to main
many thanks

uk-bolly
