### ISSUE TITLE
Task 1.2.2 regex does not adequately search for and update yum gpgcheck keys

### ISSUE THREAD

**Issue by exZACHly** [ansible-lockdown/RHEL8-CIS#425]
**Describe the Issue**
Task **1.2.2 | PATCH | Ensure gpgcheck is globally activated | Update yum.repos** does not update `gpgcheck` key in yum repo files if spaces are used in key definition. The included (default) regular expression looks for lines that start with `gpgcheck=0` rather than lines that start with the same, but may include spaces around the `=` as a valid definition.

**Expected Behavior**
If spaces are used in a key definition in a yum repo file (such as `gpgcheck = 0` instead of `gpgcheck=0`) the regular expression should update the key, as it is valid with spaces.

**Actual Behavior**
The regular expression included in the Task only finds `gpgcheck` and replaces key definitions in yum repo files that do not include spaces in the definition.

**Control(s) Affected**
RHEL8-CIS Control 1.2.2

**Environment (please complete the following information):**
- branch being used: **tag 3.0.1**
- Ansible Version: **2.11**
- Host Python Version: **Python 3.6.8**
- Ansible Server Python Version: **Python 3.6.8**
- Additional Details: N/A

**Additional Notes**
N/A

**Possible Solution**
Change `regexp` Ansible parameter in Task 1.2.2 (line 42):
- from: `"^gpgcheck=0"` 
- to: `'^gpgcheck\s*=\s*0'`

Note: Zero or more spaces around the `=` is considered valid. Single quotes around expression due to escaped characters (`\s`). Double quotes will cause the expression to fail.

**Comment by uk-bolly** [comment]
hi @exZACHly 

Thank you again for this feedback. This has now been merged into the main branch for a release. I will therefore close this issue. Please reopen if you feel this is still an issue.

Kindest regards

uk-bolly
