### ISSUE TITLE
Error missing vars - post_remediation_audit.yml

### ISSUE THREAD

**Issue by txsastre** [ansible-lockdown/RHEL8-CIS#432]
**Describe the Issue**
when doing an audit exercise it does not finish because in  Post Audit it says that there are unknown vars

**Expected Behavior**
to end properly the audit

TASK [/home/aemer/ansible/hardening/RHEL8-CIS : Post Audit | Run post_remediation RHEL8-CIS audit] ***************************************************************************
fatal: [RL8-1]: FAILED! => {"msg": "The field 'environment' has an invalid value, which includes an undefined variable. The error was: 'audit_bin' is undefined. 'audit_bin' is undefined\n\nThe error appears to be in '/home/aemer/ansible/hardening/RHEL8-CIS/tasks/post_remediation_audit.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Post Audit | Run post_remediation {{ benchmark }} audit\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

**Actual Behavior**
it stops, at this moment in post_remediation_audit.yml
in pre process this step exists but is skipped

the vars are inside de files
audit_conf_dir }}/run_audit.sh -v {{ audit_vars_path }} -f {{ audit_format }} -o {{ post_audit_outfile }} -g \"{{ group_names

**Control(s) Affected**
What controls are being affected by the issue

**Environment (please complete the following information):**

- branch being used: devel
$ ansible --version
ansible [core 2.16.3]
  config file = /home/aemer/ansible/ansible.cfg
  configured module search path = ['/home/aemer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/aemer/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.5 (main, Sep 24 2024, 14:11:40) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22.0.1)] (/usr/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True

**Additional Notes**
Anything additional goes here

**Possible Solution**
check why this step is skipped on pre and why are these vars missing. I cannot see where are they initialized

**Comment by txsastre** [comment]
The problem is when setting the run_audit: variable to true

**Comment by uk-bolly** [comment]
hi @txsastre 

Think i missed the chat on discord?
Can you please confirm the settings you are using to run the controls and some idea of the run so we can see the details of what is occuring? If you could let us know if you are using tags etc as well.
Just checking you are setting run_audit true in what location and how? e.g. inventory, extra vars etc

The reason i'm asking is audit bin is set permanently in vars/audit.yml which is loaded as part of the prelim play so we need to see what is being set that causes this.

Many thanks

uk-bolly

**Comment by txsastre** [comment]
Hi there. Don't worry about the chat, I don't want to be too intrusive.

The way I work with your playbook is like this.

I have created different files, with different values to its variables, at this moment I use remediation and auditing files, for example:

` ansible-playbook -i inventory/local.ini hardening/RHEL8-CIS/site.yml -l RL8-1 **-e @hardening/vars/rhel8-rem-vars.yml**
`
The **rhel8-rem-vars.yml** is a copy of **/defaults/main.yml**, also it's in another directory, so when I upgrade the playbook I don't lose the configuration. I don't know if this playbook is meant to be use like this, but for me it's ok, because I can set ad-hoc rules I want to audit. For example, I have **-e @hardening/vars/rhel8-_aud_-vars.yml** for audit, so you can see better what I'm talking about.

As I said, if using the playbook as remediate it works ok, when using it as audit it makes the error related, by the way the previous version did work fine for me.

**this is a piece of rhel8 -e @hardening/vars/aud_-vars.yml**

```
###########################################
### Goss is required on the remote host ###
### vars/auditd.yml for other settings  ###

# Allow audit to setup the requirements including installing git (if option chosen and downloading and adding goss binary to system)
setup_audit: false

# enable audits to run - this runs the audit and get the latest content
**run_audit: true**
# Run heavy tests - some tests can have more impact on a system enabling these can have greater impact on a system
audit_run_heavy_tests: true

## Only run Audit do not remediate
**audit_only: true**
### As part of audit_only ###
# This will enable files to be copied back to control node in audit_only mode
fetch_audit_files: true

# Path to copy the files to will create dir structure in audit_only mode
audit_capture_files_dir: /tmp
#############################

# How to retrieve audit binary
# Options are copy or download - detailed settings at the bottom of this file
# you will need to access to either github or the file already dowmloaded
get_audit_binary_method: copy

## if get_audit_binary_method - copy the following needs to be updated for your environment
## it is expected that it will be copied from somewhere accessible to the control node
## e.g copy from ansible control node to remote host
audit_bin_copy_location: /usr/local/bin/goss

# how to get audit files onto host options
# options are git/copy/archive/get_url other e.g. if you wish to run from already downloaded conf
audit_content: archive

# If using either archive, copy, get_url:
## Note will work with .tar files - zip will require extra configuration
### If using get_url this is expecting github url in tar.gz format e.g.
### https://github.com/ansible-lockdown/UBUNTU22-CIS-Audit/archive/refs/heads/benchmark-v1.0.0.tar.gz
audit_conf_source: /home/{{user_ansible_cgi}}/ansible/hardening/RHEL8-CIS-Audit.tar.gz

# Destination for the audit content to be placed on managed node
# note may not need full path e.g. /opt with the directory being the {{ benchmark }}-Audit directory
audit_conf_dest: "/opt"
```

# Where the audit logs are stored
audit_log_dir: '/opt'

### Goss Settings ##
####### END ########

**Comment by uk-bolly** [comment]
hi @txsastre 

If you add a debug what is the value of audit_bin?
The variable is set in the vars/audit.yml file. 
Trying to work it out are you running an audit_only or/and run_audit?

Audit only will only run one audit, run_audit is to be run as part of the remedation.

Using the default settings with run_audit: true or false  or audit_only: true this works with all as expected.

Thanks

uk-bolly

**Comment by txsastre** [comment]
If I set 
run_audit: true 

that's what I get


the result is "TASK [/home/aemer/ansible/hardening/RHEL8-CIS : Post Audit | Run post_remediation RHEL8-CIS audit] **************************************************************************
fatal: [RL8-1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'audit_conf_dir' is undefined\n\nThe error appears to be in '/home/aemer/ansible/hardening/RHEL8-CIS/tasks/post_remediation_audit.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Post Audit | Run post_remediation {{ benchmark }} audit\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}"

**Comment by txsastre** [comment]
on the other hand if I do 
run_audit: false
audit_only: true

it runs ok, but I cannot find the the audit files
I have it this way.
```

# Allow audit to setup the requirements including installing git (if option chosen and downloading and adding goss binary to system)
setup_audit: false

# enable audits to run - this runs the audit and get the latest content
run_audit: false 
# Run heavy tests - some tests can have more impact on a system enabling these can have greater impact on a system
audit_run_heavy_tests: true

## Only run Audit do not remediate
audit_only: true
### As part of audit_only ###
# This will enable files to be copied back to control node in audit_only mode
fetch_audit_files: true

# Path to copy the files to will create dir structure in audit_only mode
audit_capture_files_dir: /tmp
#############################

# How to retrieve audit binary
# Options are copy or download - detailed settings at the bottom of this file
# you will need to access to either github or the file already dowmloaded
get_audit_binary_method: copy

## if get_audit_binary_method - copy the following needs to be updated for your environment
## it is expected that it will be copied from somewhere accessible to the control node
## e.g copy from ansible control node to remote host
audit_bin_copy_location: /usr/local/bin/goss

# how to get audit files onto host options
# options are git/copy/archive/get_url other e.g. if you wish to run from already downloaded conf
audit_content: archive

# If using either archive, copy, get_url:
## Note will work with .tar files - zip will require extra configuration
### If using get_url this is expecting github url in tar.gz format e.g.
### https://github.com/ansible-lockdown/UBUNTU22-CIS-Audit/archive/refs/heads/benchmark-v1.0.0.tar.gz
audit_conf_source: /home/{{user_ansible_cgi}}/ansible/hardening/RHEL8-CIS-Audit.tar.gz

# Destination for the audit content to be placed on managed node
# note may not need full path e.g. /opt with the directory being the {{ benchmark }}-Audit directory
audit_conf_dest: "/opt"

# Where the audit logs are stored
audit_log_dir: '/opt'

### Goss Settings ##


```
