### ISSUE TITLE
1.2.2 recommendation depends rhel8cis_rule_1_2_5 switch

### ISSUE THREAD

**Issue by sashaCher** [ansible-lockdown/RHEL8-CIS#57]
1.2.2 recommendation "[Disable the rhnsd Daemon](https://github.com/ansible-lockdown/RHEL8-CIS/blob/39579bf1cea4f2069ce95362c87a46340e795467/tasks/section1.yml#L373)" depends rhel8cis_rule_1_2_5 switch.
There's unused [rhel8cis_rule_1_2_2](https://github.com/ansible-lockdown/RHEL8-CIS/blob/39579bf1cea4f2069ce95362c87a46340e795467/defaults/main.yml#L53) switch in main.yml

**Comment by georgenalen** [comment]
Fixed, this was a typo. Thanks for finding it and pointing it out! I will merge change up through devel and main.
