### ISSUE TITLE
Rules 2.2.1.2 and 2.2.1.3 repeat each other 

### ISSUE THREAD

**Issue by sashaCher** [ansible-lockdown/RHEL8-CIS#58]
Rules [2.2.1.2](https://github.com/ansible-lockdown/RHEL8-CIS/blob/39579bf1cea4f2069ce95362c87a46340e795467/tasks/section2.yml#L26) and [2.2.1.3](https://github.com/ansible-lockdown/RHEL8-CIS/blob/39579bf1cea4f2069ce95362c87a46340e795467/tasks/section2.yml#L52) repeat each other.
RHEL 8 CIS Benchmark has no 2.2.1.3 rule.

**Comment by georgenalen** [comment]
Fixed, this was a typo and 2.2.1.2 was left over from copying/pasting. Thanks for finding it and pointing it out! I will merge change up through devel and main.
