### ISSUE TITLE
Sections 1.2.3 - 1.1.5 do not account for /tmp defined in /etc/fstab

### ISSUE THREAD

**Issue by ag-wood** [ansible-lockdown/RHEL8-CIS#59]
The implementation assumes that /tmp is mounted by tmp.mount but the CIS document does not require this as it is also valid to continue to use /etc/fstab.

**Comment by ag-wood** [comment]
Fixed by #60

**Comment by georgenalen** [comment]
hello, This issue was addressed with PR #83
