### ISSUE TITLE
Variable not defined in parse_etc_password

### ISSUE THREAD

**Issue by ag-wood** [ansible-lockdown/RHEL8-CIS#61]
Multiple references to undefined variable [rhel8cis_passwd_tasks](https://github.com/ansible-lockdown/RHEL8-CIS/blob/39579bf1cea4f2069ce95362c87a46340e795467/tasks/parse_etc_password.yml#L2)

**Comment by georgenalen** [comment]
Thanks for pointing that out, the fix will be in the next release.
