### ISSUE TITLE
Mismatch between 4.1.12 and 4.1.13 rules

### ISSUE THREAD

**Issue by sashaCher** [ansible-lockdown/RHEL8-CIS#65]
There's some mismatch between [4.1.12](https://github.com/ansible-lockdown/RHEL8-CIS/blob/39579bf1cea4f2069ce95362c87a46340e795467/tasks/section4.yml#L268) _Ensure successful file system mounts are collected_ and [4.1.13](https://github.com/ansible-lockdown/RHEL8-CIS/blob/39579bf1cea4f2069ce95362c87a46340e795467/tasks/section4.yml#L292) _Ensure use of privileged commands is collected_ implementation.
They has the same name and the implementation blocks dislocated.

**Comment by georgenalen** [comment]
Fixed, this was a typo and names have been updated. Thanks for finding it and pointing it out! I will merge change up through devel and main.
