### ISSUE TITLE
5.2.20 recommendation depends rhel8cis_rule_5_2_19 switch

### ISSUE THREAD

**Issue by sashaCher** [ansible-lockdown/RHEL8-CIS#66]
5.2.20 recommendation "[Ensure system-wide crypto policy is not over-ridden](https://github.com/ansible-lockdown/RHEL8-CIS/blob/39579bf1cea4f2069ce95362c87a46340e795467/tasks/section5.yml#L437)" depends rhel8cis_rule_5_2_19 switch.
There's unused [rhel8cis_rule_5_2_20](https://github.com/ansible-lockdown/RHEL8-CIS/blob/39579bf1cea4f2069ce95362c87a46340e795467/defaults/main.yml#L222) switch in main.yml

**Comment by georgenalen** [comment]
Fixed, this was a typo in the when and I adjusted to have the correct reference. Thanks for finding it and pointing it out! I will merge change up through devel and main.
