### ISSUE TITLE
Unused prelim code for 6.2.8 has incorrect bash expansion

### ISSUE THREAD

**Issue by dmacduff** [ansible-lockdown/RHEL8-CIS#73]
In task `"PRELIM | 6.2.8 | Gather local interactive user directories"`, the
`getent passwd { {{ rhel8cis_int_gid }}..65535}` results in failed bash expansion due to the space after the first `{`.

The code:
`shell: "getent passwd { {{ rhel8cis_int_gid }}..65535} | cut -d: -f6 | sort -u | grep -v '/var/' | grep -v '/nonexistent/*' | grep -v '/run/*'"`
could be rewritten with a join filter, e.g.:
`shell: "{{ [ 'getent passwd {', '..65535} | cut -d: -f6 | sort -u | grep -v /var/ | grep -v /nonexistent/ | grep -v /run/' ] | join(rhel8cis_int_gid) }}"`

However, the variables registered by this and the subsequent task in prelim.yml (`"PRELIM | 6.2.8 | Set fact for home directory paths for interactive users"`) do not appear to be used anywhere else in the role. As the logic of these tasks does not seem to map exactly to the 6.2.8 rule in the benchmark, nor are these results used in task `"SCORED | 6.2.8 | PATCH | Ensure users own their home directories"` in section6.yml, I recommend removing these two tasks from prelim.yml.

**Comment by georgenalen** [comment]
Fixed with PR #75, thanks for pointing this out.

-George
