### ISSUE TITLE
Bug in 1.3.2/1.3.3

### ISSUE THREAD

**Issue by raspinall** [ansible-lockdown/RHEL8-CIS#82]
The regex's in item 1.3.2 and 1.3.3 conflict with each other.  By running the role in step mode, you can verify that
"Defaults    use_pty" in /etc/sudoers is present after 1.3.2, and then immediately replaced by
"Defaults    logfile="/var/log/sudo.log"" in task 1.3.3, because the regex for both tasks is:

"^Defaults"

I suggest changing the regex for task 1.3.2 to `'^Defaults    (?!(logfile="{{ rhel8cis_varlog_location }}")).*'`
and the regex for task 1.3.3 to `'^Defaults    (?!(use_pty)).*'`

In the above two regex, there are 4 spaces between "Defaults" and the rest of the regex, but I can't get that to format correctly here.

**Comment by georgenalen** [comment]
Thanks for  reporting the issue. This will be addressed in the next release. We are working on a goss framework audit, similar to the RHEL7-CIS/STIG and I discovered this issue and a few others. The hope is to have that release in the next couple of weeks.
