### ISSUE TITLE
Error with rhel8cis_rule_6_1_1

### ISSUE THREAD

**Issue by jeromesteunenberg** [ansible-lockdown/RHEL8-CIS#87]
The shell command rpm -Va --nomtime --nosize --nomd5 --nolinkto > /bin/{{ rhel8cis_6_1_1_packages.stdout_lines }} generates a /bin/'[.,' file.
Also, the rpm -qf step where we determine which package a file is in is missing.

**Comment by uk-bolly** [comment]
hi @jeromesteunenberg 

Thank you for raising this issue. We will be looking at this to correct the issue you have seen. If you have managed to find a resolution to this already please feel free to raise a PR.

Thanks uk-bolly

**Comment by uk-bolly** [comment]
hi @jeromesteunenberg 

We believe the issue you have raised has now been resolved and is now merged into devel. 
Please let us know if you are still seeing this issue?

Thanks

uk-bolly
