### ISSUE TITLE
Section 2.2.12 error "Could not find the requested service nfs: host" for NFS service

### ISSUE THREAD

**Issue by danderemer** [ansible-lockdown/RHEL8-CIS#90]
The NFS service definition in Section 2.2.12 lists the NFS service as just 'nfs' instead of 'nfs-server' when the 'nfs-utils' package is installed. Playbook errors out with "msg: Could not find the requested service nfs: host" when running full playbook or just 'nfs' tag. Changing the service from 'nfs' to 'nfs-server' satisfies the service check for section 2.2.12.

The issue is with the CIS benchmark for RHEL 8 version 1.0.0 document specifying the remediation step as running `systemctl --now disable nfs` instead of `systemctl --now disable nfs-server` which is necessary to satisfy the requirement of reducing the attack surface of the host if the host is not exporting shares. Understanding that the issue is with misrepresented information in the Benchmark document, the best approach for ensuring correct operation of this playbook would be to correct the service name from "nfs" to "nfs-server".

This issue was encountered on both RHEL 8.3 and CentOS 8.3. The NFS server service previously was named 'nfs' in RHEL/CentOS 6 but changed to 'nfs-server' sometime around RHEL 7.1 or 7.2.

**Comment by uk-bolly** [comment]
Hi @danderemer 

Thank you for your feedback and great explanation.
I have issued a new pull request to cover this off and hope to get this pushed in the next few days.
Please feel free to create a PR for any issues that you may find like this (there is a Contrib guide that should help).

Regards

uk-bolly

**Comment by Thulium-Drake** [comment]
Confirmed fixed on the ```april_2021_fixes``` branch :-)
