### ISSUE TITLE
5.2.3 and 5.2.4 are not idempotent (use of command module)

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-lockdown/RHEL8-CIS#94]
These modules are not idempotent because of their use of the command module.

```
TASK [cis_hardening_el8 : SCORED | 5.2.3 | PATCH | Ensure permissions on SSH private host key files are configured] ***
changed: [ansible.lbhr.htm.lan] => (item=find /etc/ssh -xdev -type f -name 'ssh_host_*_key' -exec chown root:root {} \;)
changed: [ansible.lbhr.htm.lan] => (item=find /etc/ssh -xdev -type f -name 'ssh_host_*_key' -exec chmod 0600 {} \;)

TASK [cis_hardening_el8 : SCORED | 5.2.4 | PATCH | Ensure permissions on SSH public host key files are configured] ***
changed: [ansible.lbhr.htm.lan] => (item=find /etc/ssh -xdev -type f -name 'ssh_host_*_key.pub' -exec chmod 0644 {} \;)
changed: [ansible.lbhr.htm.lan] => (item=find /etc/ssh -xdev -type f -name 'ssh_host_*_key.pub' -exec chown root:root {} \;)
```

**Comment by georgenalen** [comment]
Thalium-Drake, 
 I changed these two controls from commands to a block with find/file modules. This will make it in the release built from the april_2021_fixes update. Thanks for raising the issue and catching this one. 

George

**Comment by Thulium-Drake** [comment]
You we're just a little bit faster then I was ;-) I also opened #95 , feel free to close that! :-)

**Comment by georgenalen** [comment]
I also just realized you have a PR for this............I will kill that one (sorry). I will look over the other PR you created. I might change that to go in to that April_2021_fixes branch.

**Comment by Thulium-Drake** [comment]
It's fine, thanks for picking it up so quickly! <3

**Comment by Thulium-Drake** [comment]
fixed in ```april_2021_fixes```
